"""SMTP email sender for watchlist and universe scorecard reports."""

from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from core.config import get_thresholds


def _get_smtp_config(config: dict[str, Any]) -> dict[str, str]:
    email_cfg = config.get("email", {})
    return {
        "host": os.environ.get("SMTP_HOST") or email_cfg.get("smtp_host", "smtp.gmail.com"),
        "port": str(os.environ.get("SMTP_PORT") or email_cfg.get("smtp_port", 587)),
        "from_address": os.environ.get("SMTP_FROM") or email_cfg.get("from_address", ""),
        "to_address": os.environ.get("SMTP_TO") or email_cfg.get("to_address", ""),
        "username": os.environ.get("SMTP_USERNAME") or email_cfg.get("from_address", ""),
        "password": os.environ.get("SMTP_PASSWORD") or "",
    }


def smtp_config_status(config: dict[str, Any]) -> tuple[bool, str]:
    """Return (ready, reason). Does not expose secrets."""
    smtp = _get_smtp_config(config)
    if not smtp["from_address"]:
        return False, "missing from address (set SMTP_FROM or email.from_address in config.yaml)"
    if not smtp["to_address"]:
        return False, "missing to address (set SMTP_TO or email.to_address in config.yaml)"
    if not smtp["password"]:
        return False, "missing SMTP password (set SMTP_PASSWORD secret or env var)"
    return True, f"from={smtp['from_address']} to={smtp['to_address']} host={smtp['host']}"


def email_is_enabled(config: dict[str, Any]) -> bool:
    email_cfg = config.get("email", {})
    return bool(email_cfg.get("enabled", False) or os.environ.get("SMTP_PASSWORD"))


def _fmt_score(value: float | None, *, suffix: str = "") -> str:
    if value is None:
        return "N/A"
    return f"{value:.1f}{suffix}"


def _sort_scorecard_results(results: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(
        results,
        key=lambda r: (
            not bool(r.get("is_good_buy")),
            -(float(r.get("composite")) if r.get("composite") is not None else -1),
            r.get("ticker", ""),
        ),
    )


def format_scorecard_email(
    results: list[dict[str, Any]],
    config: dict[str, Any],
    *,
    title: str,
    subtitle: str = "",
) -> tuple[str, str]:
    """Return (subject, html_body) for a full scorecard email."""
    thresholds = get_thresholds(config)
    buy_count = sum(1 for r in results if r.get("is_good_buy"))
    subject = f"Stock Metrics: {title} ({buy_count} Buy / {len(results)} total)"

    rows = []
    for a in _sort_scorecard_results(results):
        analyst = a.get("analyst", {}) or {}
        bargain_score = (a.get("bargain") or {}).get("score")
        upside = analyst.get("implied_upside_pct")
        is_buy = bool(a.get("is_good_buy"))
        verdict = "Buy" if is_buy else "Not Buy"
        verdict_color = "#166534" if is_buy else "#6b7280"
        verdict_bg = "#dcfce7" if is_buy else "#f3f4f6"

        rows.append(
            f"<tr>"
            f"<td><b>{a.get('ticker', '')}</b></td>"
            f"<td>{a.get('name', '')}</td>"
            f"<td align='right'>{_fmt_score(a.get('composite'))}</td>"
            f"<td align='right'>{_fmt_score(bargain_score)}</td>"
            f"<td align='right'>{_fmt_score(upside, suffix='%')}</td>"
            f"<td align='center' style='background:{verdict_bg};color:{verdict_color};"
            f"font-weight:700;'>{verdict}</td>"
            f"</tr>"
        )

    subtitle_html = f"<p>{subtitle}</p>" if subtitle else ""
    table_body = (
        "".join(rows)
        if rows
        else "<tr><td colspan='6'><i>No tickers scored.</i></td></tr>"
    )

    html = f"""
    <html><body style="font-family:Arial,sans-serif;color:#1f2937;">
    <h2>{title}</h2>
    {subtitle_html}
    <p style="color:#6b7280;font-size:14px;">
    Buy criteria: composite &ge; {thresholds['composite_min']},
    bargain &ge; {thresholds['bargain_min']},
    upside &ge; {thresholds['implied_upside_min_pct']}%,
    consensus not Sell.
    </p>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%;max-width:900px;">
    <tr style="background:#f9fafb;">
      <th align="left">Ticker</th>
      <th align="left">Name</th>
      <th align="right">Composite</th>
      <th align="right">Bargain</th>
      <th align="right">Upside</th>
      <th align="center">Verdict</th>
    </tr>
    {table_body}
    </table>
    <p style="color:#9ca3af;font-size:12px;margin-top:16px;">
    <i>Generated by financial-tools.</i>
    </p>
    </body></html>
    """
    return subject, html


def format_alert_email(alerts: list[dict[str, Any]], config: dict[str, Any]) -> tuple[str, str]:
    """Legacy wrapper — formats good-buy alerts as a scorecard."""
    return format_scorecard_email(
        alerts,
        config,
        title=f"Good Buy Alerts ({len(alerts)})",
    )


def send_email(subject: str, html_body: str, config: dict[str, Any]) -> bool:
    smtp = _get_smtp_config(config)
    if not smtp["from_address"] or not smtp["to_address"] or not smtp["password"]:
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp["from_address"]
    msg["To"] = smtp["to_address"]
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(smtp["host"], int(smtp["port"])) as server:
        server.starttls()
        server.login(smtp["username"], smtp["password"])
        server.sendmail(smtp["from_address"], [smtp["to_address"]], msg.as_string())
    return True
