"""SMTP email sender for good-buy alerts."""

from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any


def _get_smtp_config(config: dict[str, Any]) -> dict[str, str]:
    email_cfg = config.get("email", {})
    return {
        "host": os.environ.get("SMTP_HOST") or email_cfg.get("smtp_host", "smtp.gmail.com"),
        "port": str(os.environ.get("SMTP_PORT") or email_cfg.get("smtp_port", 587)),
        "from_address": os.environ.get("SMTP_FROM") or email_cfg.get("from_address", ""),
        "to_address": os.environ.get("SMTP_TO") or email_cfg.get("to_address", ""),
        "username": os.environ.get("SMTP_USERNAME") or email_cfg.get("from_address", ""),
        "password": os.environ.get("SMTP_PASSWORD") or "",
    }


def format_alert_email(alerts: list[dict[str, Any]], config: dict[str, Any]) -> tuple[str, str]:
    """Return (subject, html_body) for alert email."""
    thresholds = config.get("thresholds", {})
    subject = f"Stock Metrics: {len(alerts)} good-buy alert(s)"

    rows = []
    for a in alerts:
        analyst = a.get("analyst", {})
        rows.append(
            f"<tr>"
            f"<td><b>{a.get('ticker')}</b></td>"
            f"<td>{a.get('name', '')}</td>"
            f"<td>{a.get('composite', 0):.1f}</td>"
            f"<td>{analyst.get('implied_upside_pct', 0):.1f}%</td>"
            f"<td>{analyst.get('consensus_label', '')}</td>"
            f"<td>${analyst.get('target_mean', 'N/A')}</td>"
            f"</tr>"
        )

    html = f"""
    <html><body>
    <h2>Good Buy Alerts</h2>
    <p>Thresholds: composite &ge; {thresholds.get('composite_min', 70)},
    upside &ge; {thresholds.get('implied_upside_min_pct', 15)}%</p>
    <table border="1" cellpadding="6" cellspacing="0">
    <tr><th>Ticker</th><th>Name</th><th>Composite</th><th>Upside</th><th>Consensus</th><th>Target</th></tr>
    {''.join(rows)}
    </table>
    <p><i>Generated by financial-tools daily check.</i></p>
    </body></html>
    """
    return subject, html


def send_email(subject: str, html_body: str, config: dict[str, Any]) -> bool:
    smtp = _get_smtp_config(config)
    if not smtp["from_address"] or not smtp["to_address"] or not smtp["password"]:
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp["from_address"]
    msg["To"] = smtp["to_address"]
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(smtp["host"], int(smtp["port"])) as server:
        server.starttls()
        server.login(smtp["username"], smtp["password"])
        server.sendmail(smtp["from_address"], [smtp["to_address"]], msg.as_string())
    return True
